apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak
  labels:
    app: keycloak
    server: keycloak
spec:
  entryPoints:
  - http
  routes:
  - kind: Rule
    match: Host(`id.karbonalpha.com`)
    middlewares:
    - name: https-redirect
      namespace: traefik
    services:
    - name: keycloak
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak-tls
  labels:
    app: keycloak
    server: keycloak
spec:
  entryPoints:
  - https
  routes:
  - kind: Rule
    match: Host(`id.karbonalpha.com`)
    services:
    - name: keycloak
      port: 80
  tls:
    certResolver: default