apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: wordpress
  labels:
    app: wordpress
    server: wordpress
spec:
  entryPoints:
  - http
  routes:
  - kind: Rule
    match: Host(`wp.karbonalpha.com`)
    middlewares:
    - name: https-redirect
      namespace: traefik
    services:
    - name: wordpress
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: wordpress-tls
  labels:
    app: wordpress
    server: wordpress
spec:
  entryPoints:
  - https
  routes:
  - kind: Rule
    match: Host(`wp.karbonalpha.com`)
    services:
    - name: wordpress
      port: 80
  tls:
    certResolver: default